version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bragbank-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bragbank
      MYSQL_USER: bragbank
      MYSQL_PASSWORD: bragbank
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: bragbank-redis
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
